/**
 * @File Name          : myclass.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * Ver       Date            Author      		    Modification
 * 1.0    9/20/2019   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class myclass {
	public myclass() {

	}

	// Line added by Georvys testing CI
	public String getAppVersion() {
		return '1.0.0';
	}
}
